# This workflow uploads a Python package to PyPI when a release is published.
# For more information, visit: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [published]  # Trigger workflow when a release is published

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Install build tools and create distributions
      - name: Build release distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build

      # Upload built distributions as artifacts for later use
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build  # Ensure the release build job is completed before this job
    permissions:
      id-token: write  # Mandatory permission for trusted publishing

    environment:
      name: pypi  # Define environment for deployment
      url: https://pypi.org/project/mailstream/  # Replace YOURPROJECT with your project name

    steps:
      # Retrieve the built distributions from artifacts
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      # Publish the distributions to PyPI
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}  # Secure token for PyPI
